build:
  image: golang:1.7-alpine
  commands:
  - echo "build commands"
  - chmod 755 .shipped
  - ls .shipped
  - ls -l .shipped/build
  - .shipped/build
  - .shipped/test
publish:
  docker:
    file: ./Dockerfile
    insecure: true
    username: $$docker_user
    password: $$docker_key
    registry: $$docker_registry
    repo: $$docker_repo
    email: $$docker_user_email
    tag: $$COMMIT
