#!/bin/bash

#curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer
go version
go get -d github.com/mf-00/minio
echo "GOPATH is: $GOPATH"
export GOROOT=/usr/local/go
cd $GOPATH/src/github.com/mf-00/minio
make

#go build -o .shipput
#cp .shipped/out /tmp/shipped-out
